### ISSUE TITLE
no associated item named `Up` found for struct `std::collections::btree_map::Keys` in the current scope

### ISSUE THREAD

**Issue by kriptonian1** [mateolafalce/k_board#2]
I came across your article on [dev.to](https://dev.to/stacy-roll/how-to-get-the-keys-without-pressing-enter-in-rust-1onf), and while following it, I came across this error.

![image](https://github.com/mateolafalce/k_board/assets/74916308/57ccf08b-c1d4-4997-8faf-f7a2ed11cc92)

this is what the error says
![image](https://github.com/mateolafalce/k_board/assets/74916308/7d92898c-8c66-4fe0-88bc-1fc7020aff31)

**Comment by kriptonian1** [comment]
@mateolafalce can you pls help me resolve this issue

**Comment by mateolafalce** [comment]
k_board without features have all arrows and enter

```rust
pub const ARROWS_ENTER: [([u8; BYTES], Keys); 5] = [
    ([0x1B, 0x5B, 0x41], Keys::Up),
    ([0x1B, 0x5B, 0x42], Keys::Down),
    ([0x1B, 0x5B, 0x43], Keys::Right),
    ([0x1B, 0x5B, 0x44], Keys::Left),
    ([0x0A, 0x00, 0x00], Keys::Enter),
];
```
It looks like VSC is taking Keys from btree_map. Check you have imported: 

```rust
use k_board::{keyboard::Keyboard, keys::Keys};
```
If you are importing Keys from btree_map, you can import just `keys`  & make a match like this: `keys::Keys::Up`

If it doesnt fix your error, send me here the code & we fix it.

Note: Remember if you want to get specific keys of the keyboard you need to add the corresponding feature, in the [crate](https://crates.io/crates/k_board) is specified everyone. k_board at the moment just support linux distributions.
